### ISSUE TITLE
Single panel for range-picker

### ISSUE THREAD

**Issue by vinayakkulkarni** [dwqs/v2-datepicker#1]
Instead of two panels, single panel for daterange picker?

<img width="588" alt="screen shot 2018-02-24 at 12 49 39 pm" src="https://user-images.githubusercontent.com/19776877/36626924-33e341e8-1961-11e8-94c2-92a00bef277f.png">

**Comment by dwqs** [comment]
When two panels have the same month, it's maybe difficult to convert two panels to a single panel.  Maybe a good way is disabled 'next month selecting' for left panel when `unlink-panels` is `true` and month is close,  just like [this](https://jsfiddle.net/api/post/library/pure/)

**Comment by vinayakkulkarni** [comment]
The jsfiddle links is wrong. can you please update it ?

**Comment by dwqs** [comment]
See here: http://element.eleme.io/2.0/#/en-US/component/date-picker#date-range

![image](https://user-images.githubusercontent.com/7871813/36630411-e0e90e9c-19a0-11e8-95c3-9717587ef068.png)
