### ISSUE TITLE
设置yyyy MM dd

### ISSUE THREAD

**Issue by xdwxls** [dwqs/v2-datepicker#11]
设置yyyy 如何将面板变成所有的年份 
类似这样
![image](https://user-images.githubusercontent.com/9478777/38929032-a1c80832-433d-11e8-87b9-a67055cc93d0.png)

MM 
![image](https://user-images.githubusercontent.com/9478777/38929066-b9546068-433d-11e8-94e1-7978f0f45788.png)

**Comment by dwqs** [comment]
这个目前暂不支持
