### ISSUE TITLE
范围日期的一个建议和一个疑似 Bug。

### ISSUE THREAD

**Issue by xiaopiao5789** [dwqs/v2-datepicker#12]
## 建议
在开启左右联动的情况下，建议增加一个选项可以设置左边面板起始月份为上个月，比如说数据查询类就并不需要未来的日期，所以一般会选择禁止未来日期。也有一些业务也是需要未来日期，比如说行程类。
## 疑似 Bug
![default](https://user-images.githubusercontent.com/28760483/39250825-fa8671a0-48cb-11e8-8594-1dad62e71f08.png)
在开启左右联动的情况下，如果给范围日期定义一个默认值为相同月份，会导致左右面板的月份相同。
问题出在
```
if (!this.unlinkPanels && diff > MONTH) {
    rightDate = (0, _utils.nextMonth)(leftDate, 1);
}
```
其中的 `diff > MONTH` 我并不明白具体用意，这一段对于左右面板联动来说，好像是多余的，在开启左右面板联动的情况下，右面板应该是起始日期的下一个月

**Comment by dwqs** [comment]
@xiaopiao5789 我刚试了最新版本  截图确认是一个 bug  会明天发一个小版本修复

**Comment by xiaopiao5789** [comment]
@dwqs 感谢作者提醒，昨天并没有仔细查阅文档。

**Comment by dwqs** [comment]
@xiaopiao5789 截图的 bug 升级到 3.0.3试试

**Comment by xiaopiao5789** [comment]
@dwqs 这个只是修复了相同日期，但是我文中表示的是「相同月份」，不好意思，都怪我放错截图
![default](https://user-images.githubusercontent.com/28760483/39284361-04cfd18a-493d-11e8-8168-47f6d5bb0a0f.png)

**Comment by dwqs** [comment]
新开了个 issue: https://github.com/dwqs/v2-datepicker/issues/13  我看下这个问题
