### ISSUE TITLE
默认值属于同一个月份时，日期面板渲染出现错误

### ISSUE THREAD

**Issue by dwqs** [dwqs/v2-datepicker#13]
![image](https://user-images.githubusercontent.com/7871813/39284510-3d73cccc-4946-11e8-9dfc-da77048527df.png)

**Comment by dwqs** [comment]
Bug 出处： https://github.com/dwqs/v2-datepicker/issues/12

**Comment by xiaopiao5789** [comment]
@dwqs 应该只要把 `diff <= 0` 改为 `diff <= MONTH` 就行了，我改成这样测试了开启以及关闭左右联动，都显示正常

**Comment by dwqs** [comment]
@xiaopiao5789 是的 多谢帮忙测试 已经修复 v3.0.5

**Comment by xiaopiao5789** [comment]
@dwqs 感谢作者的辛勤劳作，非常感谢
