### ISSUE TITLE
Lang change is not reactive

### ISSUE THREAD

**Issue by nelson6e65** [dwqs/v2-datepicker#19]
I used a data variable for the current locale. I try to bind with `lang` prop of `<v2-datepicker>`, but I _must_ reload the page to apply the datepick lang change.

```vue
<v2-datepicker v-else :lang="locale"></v2-datepicker>
```

**Comment by dwqs** [comment]
I will check it

**Comment by nelson6e65** [comment]
Also, other props in the picker panel are not reactive (like default date or current date if I set from javascript instead of clicking).

I think is because this info is only changed when initialized, and do not changes (L144 for `lang`, for example):

https://github.com/dwqs/v2-datepicker/blob/65eeca6b38c0da5e13700dfb0d52272675e7a80e/components/date-picker/index.vue#L139-L151

Maybe some actions in the content of this conditional should be handled separately.

**Comment by dwqs** [comment]
Yes, some prop of the component only changed when initialized.  Maybe should add some methods to listen to the prop changed.

**Comment by dwqs** [comment]
fix it in `v3.1.0`: https://github.com/dwqs/v2-datepicker/releases/tag/v3.1.0
