### ISSUE TITLE
Bug when manually select data range

### ISSUE THREAD

**Issue by cosimolemma** [dwqs/v2-datepicker#3]
Hi,
when I try to select manually from the calendar a range the dates are subtracted of a day. 

Example in DD/MM/YYYY
Range: 01/02/2018 - 16/02/2018

I get this values in the v-model variable:
Range[0] => 2018-01-31T23:00:00.000Z
Range[1] => 2018-02-15T23:00:00.000Z

No problem, instead, when I use picker options.

Bug?

**Comment by dwqs** [comment]
Can you show me the code?

**Comment by cosimolemma** [comment]
@dwqs just solved. Thank you.
I didn't notice the "Z" in the timestamp meaning UTC timezone. It was sufficient to perform a conversion to my timezone. Thanks
